services:
  bot:
    build: .
    container_name: aiogram-bot
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge